[2025-10-18T04:30:35.619+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.distribution.upload_to_cloud_storage manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:30:35.624+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.distribution.upload_to_cloud_storage manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:30:35.624+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-10-18T04:30:35.631+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): distribution.upload_to_cloud_storage> on 2025-10-18 02:31:24.144743+00:00
[2025-10-18T04:30:35.633+0000] {standard_task_runner.py:57} INFO - Started process 1170 to run task
[2025-10-18T04:30:35.634+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agricultural_sri_annual_report', 'distribution.upload_to_cloud_storage', 'manual__2025-10-18T02:31:24.144743+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/agricultural_sri_pipeline.py', '--cfg-path', '/tmp/tmp50iwxdug']
[2025-10-18T04:30:35.635+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask distribution.upload_to_cloud_storage
[2025-10-18T04:30:35.654+0000] {task_command.py:416} INFO - Running <TaskInstance: agricultural_sri_annual_report.distribution.upload_to_cloud_storage manual__2025-10-18T02:31:24.144743+00:00 [running]> on host 4e2b74bc69c8
[2025-10-18T04:30:35.680+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alerts@agcompany.com' AIRFLOW_CTX_DAG_OWNER='agricultural_risk_team' AIRFLOW_CTX_DAG_ID='agricultural_sri_annual_report' AIRFLOW_CTX_TASK_ID='distribution.upload_to_cloud_storage' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T02:31:24.144743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T02:31:24.144743+00:00'
[2025-10-18T04:30:35.827+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/agricultural_sri_pipeline.py", line 533, in upload_to_cloud_storage
    from cloud_uploader import upload_all_reports
ImportError: cannot import name 'upload_all_reports' from 'cloud_uploader' (/opt/airflow/dags/scripts/reporters/cloud_uploader.py)
[2025-10-18T04:30:35.832+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=agricultural_sri_annual_report, task_id=distribution.upload_to_cloud_storage, execution_date=20251018T023124, start_date=20251018T043035, end_date=20251018T043035
[2025-10-18T04:30:35.836+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task distribution.upload_to_cloud_storage (cannot import name 'upload_all_reports' from 'cloud_uploader' (/opt/airflow/dags/scripts/reporters/cloud_uploader.py); 1170)
[2025-10-18T04:30:35.855+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-18T04:30:35.865+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
